### ISSUE TITLE
crossc2无法上线linux

### ISSUE THREAD

**Issue by websecer** [TryGOTry/CobaltStrike_Cat_4.5#10]
crossc2无法上线linux

**Comment by W01fh4cker** [comment]
很正常，因为`crossc2`只支持到`cs4.4`，这个`4.5`。

**Comment by TryGOTry** [comment]
估计是你crossC2生成时候配置有问题,我测试是可以上线的。
<img width="1170" alt="图片" src="https://user-images.githubusercontent.com/50934786/222882621-57f94b3b-520f-4bdc-8637-9a5149aed5f9.png">
