### ISSUE TITLE
请问一下Linux 客户端启动文件怎么写

### ISSUE THREAD

**Issue by 0xorOne** [TryGOTry/CobaltStrike_Cat_4.5#15]

**Comment by 0xorOne** [comment]
![image](https://user-images.githubusercontent.com/125463022/226161815-9cc226b9-ecb3-4f52-9778-3667c4435fcd.png)
报了这个错误，我的run文件是
```shell
java -javaagent:patch.jar -jar cat_client.jar client
```

**Comment by TryGOTry** [comment]
你这个是没有图形化界面提示...没有图形化怎么启动客户端

**Comment by 0xorOne** [comment]
那请问linux客户端该怎么设置呢
