### ISSUE TITLE
使用cloudfireCDN+profile失败

### ISSUE THREAD

**Issue by kuA35sSaasd** [TryGOTry/CobaltStrike_Cat_4.5#20]
生成beacon能上线，但是无法执行任何命令和使用功能，包括sleep
![image](https://user-images.githubusercontent.com/104559292/233880402-ba54a5cc-8584-4904-9ece-22861a053056.png)

生成artifact直接不能上线
![image](https://user-images.githubusercontent.com/104559292/233880204-98aef86b-d0c9-489b-8236-8fc2d51be89e.png)

抓包发现能正常请求到js
profile如下，只改了这个证书密码
![image](https://user-images.githubusercontent.com/104559292/233880448-2b479dce-bee1-4927-b513-067b95783ec1.png)

cloudflare已配置缓存绕过，通过IP beacon和artifact都能上线

**Comment by TryGOTry** [comment]
cdn配置需要改对应profile
