### ISSUE TITLE
SMB横向的问题

### ISSUE THREAD

**Issue by yiyhuan** [TryGOTry/CobaltStrike_Cat_4.5#21]
表哥，我去看了看catcs4.4，一样有老表提问了这个问题，
![图片](https://user-images.githubusercontent.com/121230186/233947190-140f8f6b-0e66-4039-909e-2ac8b55b4c1d.png)
利用psexec 横向的时候，选择session的时候不会出现弹窗，这个是我用其他版本的截图
![图片](https://user-images.githubusercontent.com/121230186/233946545-eeedbc64-d7b8-4a0c-9fa2-f2a0b265a7e4.png)
希望表哥能够修复这个bug！！！！！！！！！！！！！！！

**Comment by TryGOTry** [comment]
可以先尝试使用命令行执行

**Comment by TryGOTry** [comment]
最新版已修复。
