### ISSUE TITLE
打不开QAQ

### ISSUE THREAD

**Issue by wqeqwdq** [TryGOTry/CobaltStrike_Cat_4.5#26]
![image](https://user-images.githubusercontent.com/88772972/236033944-84702adb-3d58-482e-b1a7-c262cf3c4211.png)

**Comment by TryGOTry** [comment]
报错很明显了，配置文件缺少字段。下载最新的带配置文件的替换就行。

**Comment by wqeqwdq** [comment]
谢谢您

**Comment by Obsidian200** [comment]
> 报错很明显了，配置文件缺少字段。下载最新的带配置文件的替换就行。

大佬，没找到带配置文件的呢，release里面只有一个jar
