### ISSUE TITLE
cat cs自带java11和java17尝试均报错,vbs双击无反应

### ISSUE THREAD

**Issue by g543fdg** [TryGOTry/CobaltStrike_Cat_4.5#27]
![image](https://user-images.githubusercontent.com/106059173/236170568-ee495a68-2946-443d-949b-6391d118d5d7.png)

**Comment by TryGOTry** [comment]
报错很明显了，配置文件缺少字段。下载最新的带配置文件的替换就行。

**Comment by xuewawa** [comment]
> 

大佬，最新的带配置文件的去哪里下载呀。。我看目前这个项目里面还是之前的那个。。

**Comment by TryGOTry** [comment]
releases就那么几个。自己看吧

**Comment by TryGOTry** [comment]
自己多加两个字段也行。
# 是否开启上线语音提醒
CatClient.OpenOnlineMusic = false
# 上线语音文件路径
CatClient.OnlineMusic = online.wav

**Comment by xuewawa** [comment]
爱你哥，我加你好友了



在 2023-05-06 15:48:58，"Try" ***@***.***> 写道：

releases就那么几个。自己看吧
