### ISSUE TITLE
横向出现问题

### ISSUE THREAD

**Issue by Q16G** [TryGOTry/CobaltStrike_Cat_4.5#28]
<img width="610" alt="image" src="https://user-images.githubusercontent.com/113832601/236613576-b0d004e2-5b87-4e18-a114-bd40b0044955.png">
进行横向的时候出现
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/113832601/236613584-59598af0-1cd4-491f-b586-ec718febecc0.png">

**Comment by TryGOTry** [comment]
哥们，提问题前可以先搜索一下吗。
https://github.com/TryGOTry/CobaltStrike_Cat_4.5/issues/21
https://github.com/TryGOTry/CobaltStrike_Cat_4.5/releases/tag/fix_PsExec
