### ISSUE TITLE
pass?

### ISSUE THREAD

**Issue by ttsite** [TryGOTry/CobaltStrike_Cat_4.5#3]
no pass?

**Comment by xcxctestnet** [comment]
yes this chinese dog didnt post it and the site he shares doesnt have it

**Comment by NickYan7** [comment]
you should go home & say goodbye to cybersecurity if u cannot even find the passwd, shame! 🤣

**Comment by xcxctestnet** [comment]
> 

i dont access horrible made chinese sites, they cant even code a front end properly

**Comment by 10feng** [comment]
give me password please

**Comment by reputati0n** [comment]
@xcxctestnet 爱用用，不用滚，惯的你臭毛病

**Comment by btUserCenter** [comment]
> > 
> 
> i dont access horrible made chinese sites, they cant even code a front end properly

silly bitch
