### ISSUE TITLE
cs会话无法派生带msf

### ISSUE THREAD

**Issue by Ifory885** [TryGOTry/CobaltStrike_Cat_4.5#32]
cs会话无法派生带msf，一直卡在这里
![image](https://github.com/TryGOTry/CobaltStrike_Cat_4.5/assets/62537001/84a9afdf-9188-4145-9816-c94c3468fade)

**Comment by TryGOTry** [comment]
可能是没有兼容，没测试过。建议用msf生成个exe传上去运行。

**Comment by Ifory885** [comment]
> 可能是没有兼容，没测试过。建议用msf生成个exe传上去运行。

好的，那后续会计划兼容吗
