### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by jiangdada6** [TryGOTry/CobaltStrike_Cat_4.5#35]
### 师傅你好！
> 5月1日版本，颜色标记功能好像不起作用。
![image](https://github.com/TryGOTry/CobaltStrike_Cat_4.5/assets/50139422/f46c9eda-1e4b-4859-9d41-2b63b0fa7fa1)

**Comment by TryGOTry** [comment]
确实有这个bug，暂时未找到解决办法。不知道哪儿改坏了，将就用吧
