### ISSUE TITLE
Two functions not work

### ISSUE THREAD

**Issue by NickYan7** [TryGOTry/CobaltStrike_Cat_4.5#4]
Great project, Hope the following two bugs will be fixed.

1. `External C2` Listener cannot work, it report error when beacon access (OpenJDK 11.0.9 on server): 
![Screenshot2023-01-17 14 58 29](https://user-images.githubusercontent.com/27906343/212830628-c8c2e32b-f84d-4547-8a67-7ef7a6d8bae1.jpg)

2. `ssh` function not work, same bug in dogcs.

**Comment by TryGOTry** [comment]
I don't know , because I don't use External C2 and ssh functions
