### ISSUE TITLE
4.5 反编译失败

### ISSUE THREAD

**Issue by 10cks** [TryGOTry/CobaltStrike_Cat_4.5#40]
![image](https://github.com/TryGOTry/CobaltStrike_Cat_4.5/assets/47177550/1160b246-9877-4398-b20c-c0ac48689928)
请问师傅有遇到这种情况吗？

**Comment by 10cks** [comment]
卡住这里不动了

**Comment by yuanyang-ai** [comment]
+1

**Comment by TryGOTry** [comment]
没遇到过，因为我没反编译过自己的

**Comment by 10cks** [comment]
> 

应该是因为改了主题的缘故
