### ISSUE TITLE
运行一段时间后会出现connection reset，需要重启服务端

### ISSUE THREAD

**Issue by grayguest** [TryGOTry/CobaltStrike_Cat_4.5#48]
[!] client (1.1.1.1) read [Manage: xxx]: Connection reset

不知道是为啥，cs4.3好像没有遇到过这个问题。

**Comment by TryGOTry** [comment]
一般是网络问题，这个是客户端重连会提示的吧

**Comment by grayguest** [comment]
哦，好的，我再观察观察，感谢作品。

**Comment by Ifory885** [comment]
![image](https://github.com/TryGOTry/CobaltStrike_Cat_4.5/assets/62537001/4ba743ba-4670-463c-8554-c91de8cb55fb)
我的也有这个问题，客户端一直在重连
