### ISSUE TITLE
似乎不能域名上线？

### ISSUE THREAD

**Issue by 1363389144** [TryGOTry/CobaltStrike_Cat_4.5#5]
通过境外CDN上线
只要listener设置的是域名不是server的ip，就不能上线
同样的方法到4.4版本就可以上线

**Comment by 1363389144** [comment]
问题好像是4.5自带的profile不适配吧，换成我4.4用的，就可以域名上线

**Comment by TryGOTry** [comment]
不太清楚，可能需要配置,自带的profile网上随便找的
