### ISSUE TITLE
有bug会导致cs界面崩溃，同时会造成cs无限重启

### ISSUE THREAD

**Issue by liuliujiu** [TryGOTry/CobaltStrike_Cat_4.5#50]
在某项目里面发现http的马有时候会造成cs界面直接崩溃，工具栏正常，回话界面显示空白；其中dns监听器稳定触发cs无限重启的bug
![56081362](https://github.com/TryGOTry/CobaltStrike_Cat_4.5/assets/26641276/f97a9ec2-549a-4499-b799-d89601fd235f)

![3555922165](https://github.com/TryGOTry/CobaltStrike_Cat_4.5/assets/26641276/295b8d61-ffc7-47c2-9861-a218352e898a)

**Comment by TryGOTry** [comment]
你用着dogcs来这个catcs项目下问问题?

这些bug都在最新的cs4.5中修复

**Comment by liuliujiu** [comment]
没注意，sorry




It＇s&nbsp;just&nbsp;you
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TryGOTry/CobaltStrike_Cat_4.5"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月9日(星期一) 下午5:50
***@***.***&gt;;
抄送:&nbsp;"It＇s just ***@***.******@***.***&gt;;
主题:&nbsp;Re: [TryGOTry/CobaltStrike_Cat_4.5] 有bug会导致cs界面崩溃，同时会造成cs无限重启 (Issue #50)





 
你用着dogcs来这个catcs项目下问问题?
 
这些bug都在最新的cs4.5中修复
