### ISSUE TITLE
server运行时报错了

### ISSUE THREAD

**Issue by bosyment** [TryGOTry/CobaltStrike_Cat_4.5#51]
![image](https://github.com/TryGOTry/CobaltStrike_Cat_4.5/assets/43529226/14615b76-2249-43d0-9c88-448b9a748b10)

**Comment by bosyment** [comment]
![image](https://github.com/TryGOTry/CobaltStrike_Cat_4.5/assets/43529226/ed04c580-a459-4ba6-ae90-4051eb7db3ab)

**Comment by TryGOTry** [comment]
哥们，报错信息不会看？
keystore密码错误

**Comment by bosyment** [comment]
好骂。
