### ISSUE TITLE
Jump内网机器时，无法选择Session

### ISSUE THREAD

**Issue by Sndav** [TryGOTry/CobaltStrike_Cat_4.5#53]
最新版5.1中，Jump内网机器可以选择psexec，wmi的地方，可以选择Listener但是无法选择Session。可以can参考下面的图片
![test](https://github.com/TryGOTry/CobaltStrike_Cat_4.5/assets/10370671/c94dba34-2b57-4db1-b923-660234222d25)

**Comment by TryGOTry** [comment]
用修复client版本。
