### ISSUE TITLE
一点击desktop-VNC自动断开连接

### ISSUE THREAD

**Issue by qwe1433223** [TryGOTry/CobaltStrike_Cat_4.5#54]
一点击desktop-VNC自动断开连接，甚至都没进入进去。不过断开连接后又恢复了。但就是不能进行桌面控制
![image](https://github.com/TryGOTry/CobaltStrike_Cat_4.5/assets/85558444/ee664993-6bda-4d83-94e2-9370d420ead5)

**Comment by TryGOTry** [comment]
报错是缺少dll文件。
在客户端目录下新建一个resources文件夹，然后把winvnc.x86.dll和winvnc.x64.dll放进去就行。
两个dll可以在其他cs原版中找到。

**Comment by qwe1433223** [comment]
好的，谢谢师傅

**Comment by qwe1433223** [comment]
测试了，没有作用

**Comment by qwe1433223** [comment]
我在resources和third-party两个文件夹都放了这两个dll，依然是闪退

**Comment by qwe1433223** [comment]
师傅，不是这个问题，我改为了readFile后之后依然是闪退。可惜我不会java。。不能深入调试

**Comment by qwe1433223** [comment]
调试结论：
64位木马上x64的dll识别为x86
32位木马上x86的dll无法建立连接。
![image](https://github.com/TryGOTry/CobaltStrike_Cat_4.5/assets/85558444/3e080233-da85-43d0-94c2-080eb99ec889)

**Comment by nannanshen** [comment]
服务端新建third-party，把dll放进去就可以了

**Comment by TryGOTry** [comment]
新版本已修复,详细看:https://www.nctry.com/2735.html
