### ISSUE TITLE
process 显示错误

### ISSUE THREAD

**Issue by ggg4566** [TryGOTry/CobaltStrike_Cat_4.5#6]
如果进程名包含go字符串好像被替换为空了
<img width="437" alt="image" src="https://user-images.githubusercontent.com/7532477/216739932-d36c9490-d736-44ba-83ed-17a473f89221.png">

**Comment by TryGOTry** [comment]
你用的geacon吧,他的获取进程名有问题。
你可以用cs自带的生成一个带go名字的马测试。

**Comment by ggg4566** [comment]
果然是，疏忽了👍
