### ISSUE TITLE
经测试加载CrossC2插件后无法上线linux机器，其他cs版本可以。是为啥啊

### ISSUE THREAD

**Issue by ssrc-c** [TryGOTry/CobaltStrike_Cat_4.5#62]

**Comment by TryGOTry** [comment]
不清楚，测试用CrossC2是可以正常上线的。
可以试试下面这个工具上线linux：
https://github.com/TryGOTry/AutoGeaconC2

**Comment by ssrc-c** [comment]
> 不清楚，测试用CrossC2是可以正常上线的。 可以试试下面这个工具上线linux： https://github.com/TryGOTry/AutoGeaconC2

哦解决了，这个默认加载了jquery-c2.4.5.profile，需要将jquery-c2.4.5.profile复制到CrossC2中，生成shell时指定";;jquery-c2.4.5.profile"即可上线
