### ISSUE TITLE
支持 agscript 吗，上线提醒的插件需要用到

### ISSUE THREAD

**Issue by Rubby2001** [TryGOTry/CobaltStrike_Cat_4.5#64]
支持 agscript 吗，上线提醒的插件需要用到

**Comment by TryGOTry** [comment]
你是不认识字吗？不是在相关命令里写了的吗？？？？

https://github.com/TryGOTry/CobaltStrike_Cat_4.5#%E7%9B%B8%E5%85%B3%E5%91%BD%E4%BB%A4
