### ISSUE TITLE
关于cs密码设置认证失败

### ISSUE THREAD

**Issue by Pizz33** [TryGOTry/CobaltStrike_Cat_4.5#7]
师傅您好 cs密码设置含英文会提示认证失败
![image](https://user-images.githubusercontent.com/88339946/216863025-6f023840-c55b-48da-9e08-1f4f13ded33c.png)
纯数字可以正常运行
![image](https://user-images.githubusercontent.com/88339946/216865833-563c77b4-5c8a-4581-b5f7-7aca08400f36.png)

想问一下这个是什么原因= =

**Comment by TryGOTry** [comment]
大哥，先好好看看README说明好吗。密码是在配置文件里改.
看都不看使用说明的吗
