### ISSUE TITLE
Mac运行后打不开呢

### ISSUE THREAD

**Issue by zhanghuaxin-dev** [TryGOTry/CobaltStrike_Cat_4.5#9]
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/59738277/220869259-5ea3c082-38fd-4c94-8681-2937f35e6200.png">

**Comment by TryGOTry** [comment]
其他系统执行:java -jar cat_client.jar client

**Comment by zhanghuaxin-dev** [comment]
谢谢，没看清到换行的说明QAQ
